### ISSUE TITLE
项目克隆下来,跑步起来  博主 你看看啥情况

### ISSUE THREAD

**Issue by ILoveLin** [githubhaohao/LearnFFmpeg#10]
`Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process C:\Users\Administrator\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\Users\Administrator\Desktop\LearnFFmpeg\app\.cxx\cmake\debug\arm64-v8a --target learn-ffmpeg}
  [1/1] Linking CXX shared library C:\Users\Administrator\Desktop\LearnFFmpeg\app\build\intermediates\cmake\debug\obj\arm64-v8a\liblearn-ffmpeg.so
  FAILED: cmd.exe /C "cd . && C:\Users\Administrator\AppData\Local\Android\Sdk\ndk\23.1.7779620\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=aarch64-none-linux-android21 --gcc-toolchain=C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/Administrator/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -std=c++11 -frtti -fexceptions -std=gnu++11 -fno-limit-debug-info  -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,liblearn-ffmpeg.so -o C:\Users\Administrator\Desktop\LearnFFmpeg\app\build\intermediates\cmake\debug\obj\arm64-v8a\liblearn-ffmpeg.so CMakeFiles/learn-ffmpeg.dir/learn-ffmpeg.cpp.o CMakeFiles/learn-ffmpeg.dir/util/GLUtils.cpp.o CMakeFiles/learn-ffmpeg.dir/common/AVPacketQueue.cpp.o CMakeFiles/learn-ffmpeg.dir/player/FFMediaPlayer.cpp.o CMakeFiles/learn-ffmpeg.dir/player/HWCodecPlayer.cpp.o CMakeFiles/learn-ffmpeg.dir/player/PlayerWrapper.cpp.o CMakeFiles/learn-ffmpeg.dir/player/decoder/AudioDecoder.cpp.o CMakeFiles/learn-ffmpeg.dir/player/decoder/DecoderBase.cpp.o CMakeFiles/learn-ffmpeg.dir/player/decoder/VideoDecoder.cpp.o CMakeFiles/learn-ffmpeg.dir/player/render/video/NativeRender.cpp.o CMakeFiles/learn-ffmpeg.dir/player/render/video/VRGLRender.cpp.o CMakeFiles/learn-ffmpeg.dir/player/render/video/VideoGLRender.cpp.o CMakeFiles/learn-ffmpeg.dir/player/render/audio/AudioGLRender.cpp.o CMakeFiles/learn-ffmpeg.dir/player/render/audio/OpenSLRender.cpp.o CMakeFiles/learn-ffmpeg.dir/recorder/SingleVideoRecorder.cpp.o CMakeFiles/learn-ffmpeg.dir/recorder/SingleAudioRecorder.cpp.o CMakeFiles/learn-ffmpeg.dir/recorder/MediaRecorderContext.cpp.o CMakeFiles/learn-ffmpeg.dir/recorder/GLCameraRender.cpp.o CMakeFiles/learn-ffmpeg.dir/recorder/MediaRecorder.cpp.o -LC:/Users/Administrator/Desktop/LearnFFmpeg/app/src/main/cpp/../jniLibs/arm64-v8a -lavformat -lavcodec -lavfilter -lswresample -lswscale -lavutil -lfdk-aac -lx264 -landroid -lmediandk -lEGL -lGLESv3 -lOpenSLES -llog -lm -lz -latomic -lm && cd ."
  ld: error: relocation R_AARCH64_ADR_PREL_PG_HI21 cannot be used against symbol ff_cos_32; recompile with -fPIC

`

**Comment by xxrlzzz** [comment]
#9 把ndk版本降成21
